spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 3s
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 2

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}

file:
  upload-dir: ${FILE_UPLOAD_DIR:C:/dev/uploads}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha

server:
  address: 0.0.0.0
  port: 8080
